### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by Vasilije1990** [btrude/jukebox-docker#1]
Hi there. 
Thanks for taking the time to make a docker image!

I am currently trying to get it to run, but I am not finding any documentation on the repo

Would you be able to add a few hints to the Readme just to help me get started? 

Thanks!

**Comment by btrude** [comment]
> Hi there.
> Thanks for taking the time to make a docker image!
> 
> I am currently trying to get it to run, but I am not finding any documentation on the repo
> 
> Would you be able to add a few hints to the Readme just to help me get started?
> 
> Thanks!

Yeah no problem, I'll put something together tonight. Wasn't sure if anyone was using it 👍
