### ISSUE TITLE
HAve trouble with co-composer mode on vast.ai

### ISSUE THREAD

**Issue by GeorgeRRHodor** [btrude/jukebox-docker#3]
First of all, thank you for providing the Docker image - you are my personal hero.

I am not a Python programmer and I only use Linux on servers our server admin has alrady set up (I come from a C++ / Windows background, but find myself more and more doing backend development for various web applications), so you've helped me a lot to streamline the process.

I already got the non-interactive modes working fine with my own version of sample.py based on the official Google ColLab and Jukebox spit out three rather strange little tunes and upsampled the sh-t out of them. All is fine.

I then tried to adapt the co-composer ColLab by throwing out references to the IPthyon-audio player (no X server over ssh) and came up with this file (that should end after the initial three previews are created: (See attachment)
[co-compose.py.txt](https://github.com/btrude/jukebox-docker/files/5271475/co-compose.py.txt)

But I always get the error message

Sampling 4144 tokens for [0,4144]. Conditioning on 0 tokens
Traceback (most recent call last):
  File "jukebox/co-compose.py", line 82, in <module>
    zs=sample_partial_window(zs, labels, sampling_kwargs, 2, top_prior, tokens_to_sample, hps)
  File "/opt/jukebox/jukebox/sample.py", line 28, in sample_partial_window
    return sample_single_window(zs, labels, sampling_kwargs, level, prior, start, hps)
  File "/opt/jukebox/jukebox/sample.py", line 56, in sample_single_window
    y = prior.get_y(labels, start)
  File "/opt/jukebox/jukebox/prior/prior.py", line 143, in get_y
    y = labels['y'].clone()
TypeError: list indices must be integers or slices, not str

I am sure I am doing some embarrasing noob thing, but I don't really know where to even start... Any help would be appreciated.

**Comment by btrude** [comment]
Hey there, thanks for using the image. This is more of an issue with that notebook but your problem here is passing plain `labels` as opposed to `labels[2]` into the `zs=sample_partial_window(zs, labels, sampling_kwargs, 2, top_prior, tokens_to_sample, hps)` call.
