### ISSUE TITLE
Downloading from gce.  ... Killed

### ISSUE THREAD

**Issue by JoeThanks67** [btrude/jukebox-docker#6]
```
root@cfeadd8dae1f:/opt/jukebox# python jukebox/sample.py --model=1b_lyrics --name=sample_1b --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=2 --hop_fraction=0.5,0.5,0.125 
...
Level:2, Cond downsample:None, Raw to tokens:128, Sample length:786432  
Downloading from gce. 
Killed
```

Always stops at the same point. Could this be related to these changes that are not yet in the image?
[https://github.com/openai/jukebox/commit/19533750203c5f5532688d7fcbc2c357b36a67b7](https://github.com/openai/jukebox/commit/19533750203c5f5532688d7fcbc2c357b36a67b7)

**Comment by btrude** [comment]
> ```
> root@cfeadd8dae1f:/opt/jukebox# python jukebox/sample.py --model=1b_lyrics --name=sample_1b --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=2 --hop_fraction=0.5,0.5,0.125 
> ...
> Level:2, Cond downsample:None, Raw to tokens:128, Sample length:786432  
> Downloading from gce. 
> Killed
> ```
> 
> Always stops at the same point. Could this be related to these changes that are not yet in the image?
> [openai/jukebox@1953375](https://github.com/openai/jukebox/commit/19533750203c5f5532688d7fcbc2c357b36a67b7)

Definitely. Didn't realize they switched hosts - the image is rebuilding now and should be available in an hour or so.

**Comment by JoeThanks67** [comment]
I tried the new image:

```
Level:2, Cond downsample:None, Raw to tokens:128, Sample length:786432
Downloading from azure
Killed

```

Weird thing. Disk space is basically available:

```
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
tmpfs           1.6G  788K  1.6G   1% /run
/dev/nvme0n1p1  243G   98G  146G  41% /
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/loop0       94M   94M     0 100% /snap/core/8935
/dev/loop2       33M   33M     0 100% /snap/amazon-ssm-agent/2996
/dev/loop1       98M   98M     0 100% /snap/core/10583
/dev/loop3       56M   56M     0 100% /snap/core18/1944
/dev/loop4       18M   18M     0 100% /snap/amazon-ssm-agent/1566
tmpfs           1.6G     0  1.6G   0% /run/user/1000

```

I'm using  a deep learning AMI (Ubuntu 18.04) version 39.0 on an g4dn.xlarge instance.

**Comment by btrude** [comment]
What is the exit code from `echo $?`?  Sounds like a memory issue and `g4dn.xlarge` only has 16gb of RAM. I would consider trying `g4dn.2xlarge` if you can.

**Comment by JoeThanks67** [comment]
```
Level:2, Cond downsample:None, Raw to tokens:128, Sample length:786432
Downloading from azure
Killed
root@df107c0acaa4:/opt/jukebox# echo $?
137
```

I will try it with a bigger AWS instance.

**Comment by JoeThanks67** [comment]
Yes, that was it. Works with g4dn.4xlarge (64 GB memory). Great!
