### ISSUE TITLE
Latest on dockerhub?

### ISSUE THREAD

**Issue by turian** [btrude/jukebox-docker#7]
Thank you again for the Dockerfile. I see that it was updated recently, but the dockerhub file is 4 months old. Should the latest master be used, or Dockerhub version?

**Comment by btrude** [comment]
Hey, nice catch 🤣 ! Looks like the build failed and I never noticed. I'll update it to pytorch 1.8 this weekend and rebuild it then. If the current hub version works for you then there will be very little difference between the updated versions.
